// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKyglbQEQjlvc09aumSnFYBgbCfvPYF4I',
    appId: '1:590732800735:web:c5864c2b43c2328d452f6a',
    messagingSenderId: '590732800735',
    projectId: 'deenify-0001',
    authDomain: 'deenify-0001.firebaseapp.com',
    storageBucket: 'deenify-0001.firebasestorage.app',
    measurementId: 'G-S5D0GKQ4CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyZw7-ISQJax4OdZEmkfno6bzsh60Mxc',
    appId: '1:590732800735:android:9cf3469beaf7bbc5452f6a',
    messagingSenderId: '590732800735',
    projectId: 'deenify-0001',
    storageBucket: 'deenify-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5IFEJum8ZimGyVFc-H_-YDgvTtSXFEo',
    appId: '1:590732800735:ios:f44ab5b18149f429452f6a',
    messagingSenderId: '590732800735',
    projectId: 'deenify-0001',
    storageBucket: 'deenify-0001.firebasestorage.app',
    iosBundleId: 'com.example.Deenify.deenify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKyglbQEQjlvc09aumSnFYBgbCfvPYF4I',
    appId: '1:590732800735:web:140b5f6b8cdaa073452f6a',
    messagingSenderId: '590732800735',
    projectId: 'deenify-0001',
    authDomain: 'deenify-0001.firebaseapp.com',
    storageBucket: 'deenify-0001.firebasestorage.app',
    measurementId: 'G-9XBHF6Q282',
  );
}
